### ISSUE TITLE
App needs to POST to the DRE APIs if reaction search returns 404 for definitions...

### ISSUE THREAD

**Issue by treyau21** [540co/ads-bpa#104]
Is the app gets 404 for a reaction term when doing a definition lookup on DRE... The app needs to do a POST request to /reactions... with JSON payload of:

{
  "reaction": "<reaction_name>"
}

**Comment by jobrieniii** [comment]
awaiting review by @lundstjb - https://github.com/540co/ads-bpa/commit/218beacc068ecae6168ea378395dfa5e977cdc78
