### ISSUE TITLE
Add admin pages to show contents of /reactions and /searches API

### ISSUE THREAD

**Issue by jobrieniii** [540co/ads-bpa#180]

**Comment by treyau21** [comment]
For the "Search Terms" and "Reactions Dictionary" links, I get the following JSON response.

```
{
  message: "Cannot read property '0' of undefined",
  request_body: { }
}
```

**Comment by treyau21** [comment]
Also... if we want to resubmit this pull request for merging... let's also change the routes around....

Instead of `/api/admin`, let's just change this to `/admin`.  I like to reserve the `/api` path for api calls only.

**Comment by jobrieniii** [comment]
Also patrick if u are able to fix, go ahead and also allow for a query parameter to be sent to the route to allow some level of pagination.  Doesn't have to be pretty but will prevent the crazy 10,000 limit I did on the reactions page.  Of course only if u have time and it doesn't take long.

**Comment by jobrieniii** [comment]
@treyau21 - did your config.js have the config.scheme and config.hostnane (or whatever it is called now)?  They were added yesterday and when the url is built in the express route it references that.  - just thinking

**Comment by jobrieniii** [comment]
@trey21 - see https://github.com/540co/ads-bpa/pull/212 for changes + explanation of findings.

**Comment by jobrieniii** [comment]
Also... after I thought about it for a moment - realized pagination really isn't needed b/c even after an exhaustive search for unique reaction terms during harvesting spikes, I don't believe we ever found more than 16k reactions... therefore, I bumped the search to find 20k for now - which should get everything even if the dictionary is fully populated.
