### ISSUE TITLE
create Runscope tests for new API routes

### ISSUE THREAD

**Issue by jobrieniii** [540co/ads-bpa#183]

**Comment by treyau21** [comment]
Hey @jobrieniii... is this still an open issue?  I'm coming through and marking things for 'Post Proposal' if we don't think we'll get to them...  I had this as a candidate, but wasn't sure of status... Thanks!

If it's open, could you change the Milestone for me...

**Comment by jobrieniii** [comment]
It is still open.

**Comment by treyau21** [comment]
k... cool... I'm going to mark as Post Proposal though this one doesn't matter as much in terms of the code lockdown because it's all config on Runscope side.

**Comment by jobrieniii** [comment]
Basically all happy cases are in place now for both prod and dev.  Also something we can continue to improve on - but at this point I am calling this one closed.

**Comment by jobrieniii** [comment]
@treyau21 - I also changed to Milestone v.4 - if issue you can change back.

**Comment by treyau21** [comment]
@jobrieniii - No that's cool... I'm just trying to get the v0.4 bucket to be `0` by 5pm.  :)  Some issues open will get pushed to Post Proposal very likely... but if it's done in time for v0.4, let's mark it that way
