### ISSUE TITLE
setup Runscope to test dre-dev using same tests

### ISSUE THREAD

**Issue by jobrieniii** [540co/ads-bpa#184]

**Comment by treyau21** [comment]
Hey @jobrieniii... is this still an open issue?  I'm coming through and marking things for 'Post Proposal' if we don't think we'll get to them...  I had this as a candidate, but wasn't sure of status... Thanks!

If it's open, could you change the Milestone for me...

**Comment by jobrieniii** [comment]
Done.  Closing and marking for v0.4.
