### ISSUE TITLE
Adding a custom definition doesn't seem to result in a saved definition

### ISSUE THREAD

**Issue by jobrieniii** [540co/ads-bpa#232]
steps I tried:
- searched for motrin
- tried to add the following definition for DYSPNOEA:
  difficult or labored breathing.

**Comment by treyau21** [comment]
@jobrieniii... the POST endpoint for definitions doesn't do a .toLowerCase() to the reaction name for the db.collection.update. (@killerbgt found it)

*\* Sorry posted this to the wrong issue... it's applicable here...

**Comment by jobrieniii** [comment]
Re-opening to ensure we fix this - since this still seems to be an issue in production.

**Comment by jobrieniii** [comment]
Re-opening to ensure we fix this - since this still seems to be an issue in production - should be fixed as part of API refactor.
