### ISSUE TITLE
When saving definition UI show's source same as definition

### ISSUE THREAD

**Issue by jobrieniii** [540co/ads-bpa#233]
Steps to reproduce:
- Searched for ADVIL
- Tried to add the following definition to DRUG INEFFECTIVE
  'It just doesn't work'

The source also showed: 'It just doesn't work'

**Comment by treyau21** [comment]
This seems to work fine locally using postman... will try through UI at some point tonight

**Comment by treyau21** [comment]
@jobrieniii... the POST endpoint for definitions doesn't do a .toLowerCase() to the reaction name for the db.collection.update.  (@killerbgt found it)

**Comment by treyau21** [comment]
This is a server side issue... the definition is being saved as the source.  Here's the source of this issue... this is lines 195-198 in the `/server/routes/reactions.js`...

```
  // Create new definition
  var newDefinition = new Definition();
  newDefinition.definition = definition;
  newDefinition.source = definition;
```

**Comment by treyau21** [comment]
*\* Still holding off on any commits until we know how we're handling changes moving forward...

**Comment by jobrieniii** [comment]
Re-opening to ensure we fix this - since this still seems to be an issue in production.

**Comment by jobrieniii** [comment]
Re-opening to ensure we fix this - since this still seems to be an issue in production - should be fixed as part of API refactor.
