### ISSUE TITLE
Intermittent test failures with route testing

### ISSUE THREAD

**Issue by jobrieniii** [540co/ads-bpa#269]
@killerbgt to provide more information on findings.

**Comment by killerbgt** [comment]
56 passing (5s)
  8 failing
  1) API Routes POST /reactions (reaction = bogus) - Positive test respond with HTTP STATUS CODE 200:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

  2) API Routes POST /reactions (reaction = bogus) - Duplicate (should be rejected) respond with HTTP STATUS CODE 422:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

  3) API Routes POST /reactions /definition (reaction = bogus | definition = foobar) - Should be ok respond with HTTP STATUS CODE 200:
     Error: expected 200 "OK", got 404 "Not Found"
      at net.js:1419:10
  4) API Routes PUT /reactions /definition (reaction = bogus | definitionIndex = 0) - Vote up - should be ok respond with HTTP STATUS CODE 200:
     Error: expected 200 "OK", got 404 "Not Found"
      at net.js:1419:10
  5) API Routes PUT /reactions /definition (reaction = bogus | definitionIndex = 0) - Vote down - should be ok respond with HTTP STATUS CODE 200:
     Error: expected 200 "OK", got 404 "Not Found"
      at net.js:1419:10
  6) API Routes POST /reactions /definition (reaction = bogus | definition = foobar) - Duplicate definition (should be rejected) respond with HTTP STATUS CODE 422:
     Error: expected 422 "Unprocessable Entity", got 404 "Not Found"
      at net.js:1419:10
  7) API Routes GET /reactions (reaction = bogus) - Postive Test respond with HTTP STATUS CODE 200:
     Error: expected 200 "OK", got 404 "Not Found"
      at net.js:1419:10
  8) API Routes DELETE /reactions (reaction = bogus) - Postive Test respond with HTTP STATUS CODE 204:
     Error: expected 204 "No Content", got 404 "Not Found"
      at net.js:1419:10

**Comment by jobrieniii** [comment]
@killerbgt do u think fixed this one with the ab close test changes?

**Comment by killerbgt** [comment]
@jobrieniii Closing for now... haven't seen it happen since we made the db.close change.
